name = "ProteinEnsembles"
uuid = "186d2b2d-8ad5-54a6-bcea-66047609c611"
authors = ["Joe G Greener <jgreener@hotmail.co.uk>"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
julia = "1"
ArgParse = "0.6"
Cairo = "0.7, 0.8"
Colors = "0.9"
Gadfly = "1.1"
ProgressMeter = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
